### ISSUE TITLE
Test Pricing Models

### ISSUE THREAD

**Issue by aciepiela** [malawski/cloudworkflowsimulator#179]

**Comment by ziaber** [comment]
SimpleModel configuration: 
billingUnitTime: 1 hour
GoogleModel configurataion:
firstBillingUnitTime: 10 minutes
billungUnitTime: 1 minute

Cost has been chosen so that hourly cost is the same in both models.

GENOME:

![exponential_score_100 000000](https://cloud.githubusercontent.com/assets/15855962/20884469/b7be27b0-baeb-11e6-83d9-6583c953f885.png)

LIGO:

![exponential_score_17 500000](https://cloud.githubusercontent.com/assets/15855962/20884485/d1fbd5be-baeb-11e6-9197-4ab42e728263.png)



MONTAGE:

![exponential_score_30 000000](https://cloud.githubusercontent.com/assets/15855962/20884507/f725ca02-baeb-11e6-8490-bf4e16d180c1.png)


SIPHT:

![exponential_score_13 555556](https://cloud.githubusercontent.com/assets/15855962/20884526/118df748-baec-11e6-815d-7911be36bf07.png)

The conslusion is that under small budgets and small deadline mostly in all types of workflows Google Pricing Model performes better than Simple Pricing Model which is propably caused by less flexability of VMs provisioning in Simple Pricing Model which in tests had large billingUnitTime compared to the Google Pricing Model.
